CREATE TABLE stocks(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    fk_uniform_id INT UNSIGNED,
    sold_to INT UNSIGNED,
    FOREIGN KEY(fk_uniform_id)
	REFERENCES uniforms(id)
	ON UPDATE CASCADE,
    FOREIGN KEY(sold_to)
	REFERENCES users(id)
	ON UPDATE CASCADE
);
